using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarmonyLib;
using UnityEngine;

namespace AIROG_WorldExpansion
{
    /// <summary>
    /// Faction courts (v1.4): every simulated faction gets a named leader and lieutenants,
    /// generated by AI to match the world's setting (procedural fallback). Figures give
    /// world events a face, can be met and killed as real NPCs (name-matched binding),
    /// and drive succession when they die.
    /// </summary>
    public static class FactionCourtSystem
    {
        private const int  COURT_LIEUTENANTS   = 2;
        private const double RAID_LT_DEATH     = 0.08; // per successful raid vs the defender
        private const double RAID_LEADER_DEATH = 0.03;

        private static bool _generationInFlight = false;

        private static readonly string[] FallbackTraits =
        {
            "ruthless", "cautious", "charismatic", "paranoid", "honorable",
            "cunning", "zealous", "pragmatic", "ambitious", "vengeful",
        };

        private static readonly string[] FallbackSyllables =
        {
            "Var", "Kel", "Dra", "Mor", "Sar", "Tho", "Ren", "Gal", "Ish", "Bran",
            "ek", "an", "os", "ira", "eth", "ul", "ara", "im", "or", "en",
        };

        // ─── Court seeding (called each minor tick) ───────────────────────────────

        /// Picks at most one faction lacking a full court and generates figures for it.
        /// One AI generation in flight at a time, so world start doesn't burst N calls.
        public static void EnsureCourts(GameplayManager manager)
        {
            if (_generationInFlight || manager == null) return;

            var factions = manager.GetCurrentFactions();
            if (factions == null) return;
            var eliminated = WorldData.CurrentState.EliminatedFactions;

            foreach (var faction in factions)
            {
                if (faction == null || faction.GetPrettyName() == "Player") continue;
                if (eliminated.Contains(faction.uuid)) continue;

                var data = WorldData.GetFactionData(faction.uuid);
                if (!data.Seeded) continue; // territory/pop seeding first, court second

                bool needLeader = data.Leader == null || (data.Leader.IsDead && data.Lieutenants.All(l => l.IsDead));
                int livingLts   = data.Lieutenants.Count(l => !l.IsDead);
                int needLts     = Math.Max(0, COURT_LIEUTENANTS - livingLts);
                if (!needLeader && needLts == 0) continue;

                _generationInFlight = true;
                GenerateCourtAsync(manager, faction, data, needLeader, needLts);
                return; // one faction per tick
            }
        }

        private static async void GenerateCourtAsync(GameplayManager manager, Faction faction,
            FactionExtData data, bool needLeader, int needLts)
        {
            try
            {
                int wanted = (needLeader ? 1 : 0) + needLts;
                List<FactionFigure> figures = null;
                try
                {
                    figures = await TryGenerateAIFigures(manager, faction, data, needLeader, needLts);
                }
                catch (Exception e)
                {
                    Debug.LogWarning($"[WorldExpansion] AI court generation failed for {data.Name}: {e.Message}");
                }

                if (figures == null) figures = new List<FactionFigure>();
                while (figures.Count < wanted)
                    figures.Add(MakeFallbackFigure(data, needLeader && figures.Count == 0));

                int turn = WorldData.CurrentState.CurrentTurn;
                int idx  = 0;
                if (needLeader)
                {
                    var leader = figures[idx++];
                    leader.Role      = "Leader";
                    leader.SinceTurn = turn;
                    // A regenerated court after a wiped-out line is a new claimant seizing power
                    bool dynastyEnded = data.Leader != null && data.Leader.IsDead;
                    data.Leader = leader;
                    WorldData.LogEvent(dynastyEnded
                        ? $"{leader.Display} has seized control of {data.Name} after the fall of its leadership."
                        : $"{data.Name} is led by {leader.Display}, known to be {leader.Trait}.", "COURT");
                }
                for (; idx < figures.Count; idx++)
                {
                    var lt = figures[idx];
                    lt.Role      = "Lieutenant";
                    lt.SinceTurn = turn;
                    data.Lieutenants.Add(lt);
                }
                // Drop long-dead lieutenants so the list doesn't grow forever
                if (data.Lieutenants.Count(l => l.IsDead) > 4)
                    data.Lieutenants.RemoveAll(l => l.IsDead);

                WorldEventsUI.MarkDirty();
                WorldData.SaveToCurrentDir();
                Debug.Log($"[WorldExpansion] Court generated for {data.Name}: " +
                          string.Join(", ", figures.Select(f => f.Display)));
            }
            catch (Exception e)
            {
                Debug.LogError($"[WorldExpansion] Court generation error: {e}");
            }
            finally
            {
                _generationInFlight = false;
            }
        }

        private static async Task<List<FactionFigure>> TryGenerateAIFigures(GameplayManager manager,
            Faction faction, FactionExtData data, bool needLeader, int needLts)
        {
            int wanted = (needLeader ? 1 : 0) + needLts;
            if (wanted <= 0) return new List<FactionFigure>();

            string univName = manager.GetCurrentUniverse()?.GetPrettyName() ?? "the world";
            string univDesc = "";
            try
            {
                univDesc = manager.GetCurrentUniverse()?.GetPotentiallyNullDescription() ?? "";
                if (univDesc.Length > 300) univDesc = univDesc.Substring(0, 300);
            }
            catch { }
            string facDesc = "";
            try { facDesc = faction.GetPotentiallyNullDescription() ?? ""; } catch { }
            if (facDesc.Length > 200) facDesc = facDesc.Substring(0, 200);

            string existing = data.Leader != null && !data.Leader.IsDead
                ? $"Their current leader is {data.Leader.Display} — do NOT reuse that name. " : "";

            string prompt =
                $"Setting: \"{univName}\". {univDesc}\n" +
                $"The faction \"{data.Name}\" ({facDesc}) needs {wanted} named figure(s): " +
                (needLeader ? "the first line is its LEADER, " : "") +
                $"{(needLts > 0 ? $"{needLts} lieutenant(s)/notable member(s)" : "")}. {existing}" +
                "Use titles and names that fit this setting's tone and genre exactly (never assume medieval fantasy). " +
                $"Return EXACTLY {wanted} line(s), each formatted as: NAME|TITLE|ONE-WORD-TRAIT\n" +
                "No other text.";

            string raw = await AIAsker.GenerateTxtNoTryStrStyle(
                AIAsker.ChatGptPromptType.GENERAL_QUESTION_ANSWERER,
                prompt,
                AIAsker.ChatGptPostprocessingType.NONE,
                forceOfficialChatgpt: false,
                forceNsfwFriendlyIfAvail: false,
                null,
                background: true,
                forceEventCheckModel: true);

            if (string.IsNullOrWhiteSpace(raw)) return null;

            var result = new List<FactionFigure>();
            foreach (var line in raw.Split('\n'))
            {
                var parts = line.Trim().TrimStart('-', '*', ' ').Split('|');
                if (parts.Length < 2) continue;
                string name  = parts[0].Trim().Trim('"');
                string title = parts[1].Trim().Trim('"');
                string trait = parts.Length > 2 ? parts[2].Trim().Trim('"').ToLower() : "";
                if (name.Length < 2 || name.Length > 60 || title.Length > 60) continue;
                result.Add(new FactionFigure { Name = name, Title = title, Trait = trait });
                if (result.Count >= wanted) break;
            }
            return result.Count > 0 ? result : null;
        }

        private static FactionFigure MakeFallbackFigure(FactionExtData data, bool isLeader)
        {
            var rng = WorldSimUtils.Rng;
            string name = FallbackSyllables[rng.Next(10)] + FallbackSyllables[10 + rng.Next(10)];
            if (rng.NextDouble() < 0.4) name += FallbackSyllables[10 + rng.Next(10)];

            string title;
            switch (data.Tag)
            {
                case "Holy":   title = isLeader ? "High Priest"  : "Zealot";      break;
                case "Demon":  title = isLeader ? "Dread Lord"   : "Harbinger";   break;
                case "Trade":  title = isLeader ? "Guildmaster"  : "Factor";      break;
                case "Empire": title = isLeader ? "Sovereign"    : "Marshal";     break;
                case "Nature": title = isLeader ? "Elder"        : "Warden";      break;
                case "Arcane": title = isLeader ? "Archmagus"    : "Adept";       break;
                case "Undead": title = isLeader ? "Lich Lord"    : "Deathspeaker"; break;
                default:       title = isLeader ? "Chieftain"    : "Captain";     break;
            }
            return new FactionFigure
            {
                Name  = name,
                Title = title,
                Trait = FallbackTraits[rng.Next(FallbackTraits.Length)],
            };
        }

        // ─── Binding figures to real NPCs (called each minor tick) ───────────────

        /// If a real GameCharacter matching a living figure's name (and faction, when the
        /// game has assigned one) exists, remember its uuid so its death drives succession.
        public static void TryBindFigures(GameplayManager manager)
        {
            try
            {
                if (SS.I?.uuidToGameEntityMap == null) return;
                var courts = WorldData.CurrentState.Factions
                    .Where(kv => !WorldData.CurrentState.EliminatedFactions.Contains(kv.Key))
                    .ToList();
                if (courts.Count == 0) return;

                foreach (var ent in SS.I.uuidToGameEntityMap.Values.OfType<GameCharacter>())
                {
                    if (ent.corpseState != GameCharacter.CorpseState.NONE) continue;
                    string charName = ent.GetPrettyName()?.Trim();
                    if (string.IsNullOrEmpty(charName) || charName.Length < 4) continue;

                    foreach (var kv in courts)
                    {
                        // A character the game has already put in a different faction can't be this court's figure
                        if (ent.faction != null && ent.faction.uuid != kv.Key) continue;

                        foreach (var fig in EnumerateFigures(kv.Value))
                        {
                            if (fig.IsDead || !string.IsNullOrEmpty(fig.BoundNpcUuid)) continue;
                            if (!NamesMatch(charName, fig.Name)) continue;
                            fig.BoundNpcUuid = ent.uuid;
                            Debug.Log($"[WorldExpansion] Bound {fig.Display} of {kv.Value.Name} to NPC {ent.uuid}");
                        }
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[WorldExpansion] Figure binding failed: {e.Message}");
            }
        }

        private static IEnumerable<FactionFigure> EnumerateFigures(FactionExtData data)
        {
            if (data.Leader != null) yield return data.Leader;
            if (data.Lieutenants == null) yield break;
            foreach (var lt in data.Lieutenants) yield return lt;
        }

        private static bool NamesMatch(string charName, string figureName)
        {
            if (string.IsNullOrEmpty(figureName) || figureName.Length < 4) return false;
            if (string.Equals(charName, figureName, StringComparison.OrdinalIgnoreCase)) return true;
            // "Warlord Kessek the Red" should still match figure "Kessek"
            return charName.IndexOf(figureName, StringComparison.OrdinalIgnoreCase) >= 0
                || figureName.IndexOf(charName, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        // ─── Death & succession ───────────────────────────────────────────────────

        [HarmonyPatch(typeof(GameCharacter), "SetAsCorpse")]
        [HarmonyPostfix]
        public static void Postfix_SetAsCorpse(GameCharacter __instance)
        {
            try { HandleCharacterDeath(__instance); }
            catch (Exception e) { Debug.LogWarning($"[WorldExpansion] Court death handling failed: {e.Message}"); }
        }

        private static void HandleCharacterDeath(GameCharacter ch)
        {
            if (ch == null) return;
            string charName = ch.GetPrettyName()?.Trim() ?? "";

            foreach (var kv in WorldData.CurrentState.Factions)
            {
                if (WorldData.CurrentState.EliminatedFactions.Contains(kv.Key)) continue;
                var data = kv.Value;

                foreach (var fig in EnumerateFigures(data))
                {
                    if (fig.IsDead) continue;
                    bool boundMatch = !string.IsNullOrEmpty(fig.BoundNpcUuid) && fig.BoundNpcUuid == ch.uuid;
                    bool nameMatch  = !boundMatch
                        && NamesMatch(charName, fig.Name)
                        && (ch.faction == null || ch.faction.uuid == kv.Key);
                    if (!boundMatch && !nameMatch) continue;

                    fig.IsDead       = true;
                    fig.BoundNpcUuid = ch.uuid;

                    bool diedNearPlayer = false;
                    try
                    {
                        var mgr = SS.I?.hackyManager;
                        diedNearPlayer = mgr?.currentPlace != null
                            && ch.ParentPl()?.GetTopLvlPlace()?.uuid == mgr.currentPlace.GetTopLvlPlace()?.uuid;
                    }
                    catch { }

                    if (fig.Role == "Leader")
                    {
                        if (diedNearPlayer)
                            data.LeaderSlainTurn = WorldData.CurrentState.CurrentTurn;
                        Succeed(data, $"{fig.Display} is dead");
                    }
                    else
                    {
                        WorldData.LogEvent($"{fig.Display}, lieutenant of {data.Name}, has been slain.", "COURT");
                        if (diedNearPlayer)
                            WorldData.QueuePlayerEvent(
                                $"{fig.Display} of {data.Name} lies dead — the faction will remember this.",
                                "FIGURE_SLAIN");
                    }
                    WorldEventsUI.MarkDirty();
                    WorldData.SaveToCurrentDir();
                    return; // one figure per corpse
                }
            }
        }

        /// Promotes the first living lieutenant to leader; if none remains, the court
        /// regenerates on a later tick as a new claimant seizing power.
        public static void Succeed(FactionExtData data, string cause)
        {
            var old = data.Leader;
            if (old != null)
            {
                data.FormerLeaders.Add(old.Display);
                while (data.FormerLeaders.Count > 6) data.FormerLeaders.RemoveAt(0);
            }

            var heir = data.Lieutenants?.FirstOrDefault(l => !l.IsDead);
            if (heir != null)
            {
                data.Lieutenants.Remove(heir);
                heir.Role      = "Leader";
                heir.SinceTurn = WorldData.CurrentState.CurrentTurn;
                data.Leader    = heir;
                WorldData.LogEvent($"{cause} — {heir.Display} now leads {data.Name}.", "COURT");
                WorldData.QueuePlayerEvent($"{cause}. {heir.Display} has taken command of {data.Name}.", "SUCCESSION");
            }
            else
            {
                data.Leader = old; // keep the dead leader on record until a new court is generated
                WorldData.LogEvent($"{cause} — {data.Name} is left leaderless. A struggle for power begins.", "COURT");
                WorldData.QueuePlayerEvent($"{cause}, leaving {data.Name} leaderless. Chaos brews within its ranks.", "SUCCESSION");
            }
        }

        /// Sim-side casualties: a successful raid can kill members of the defender's court.
        public static void RollRaidCasualty(FactionExtData defender, string attackerName)
        {
            var rng = WorldSimUtils.Rng;
            var lt = defender.Lieutenants?.FirstOrDefault(l => !l.IsDead && string.IsNullOrEmpty(l.BoundNpcUuid));
            if (lt != null && rng.NextDouble() < RAID_LT_DEATH)
            {
                lt.IsDead = true;
                WorldData.LogEvent($"{lt.Display} of {defender.Name} was killed in {attackerName}'s raid.", "COURT");
                return;
            }
            var leader = defender.Leader;
            if (leader != null && !leader.IsDead && string.IsNullOrEmpty(leader.BoundNpcUuid)
                && rng.NextDouble() < RAID_LEADER_DEATH)
            {
                leader.IsDead = true;
                Succeed(defender, $"{leader.Display} fell defending {defender.Name} against {attackerName}");
            }
        }

        /// Called when a faction is eliminated: settle the fate of its leader.
        public static void OnFactionEliminated(FactionExtData loser, string victorName)
        {
            var leader = loser.Leader;
            if (leader == null || leader.IsDead) return;
            if (WorldSimUtils.Rng.NextDouble() < 0.5)
            {
                leader.IsDead = true;
                WorldData.LogEvent($"{leader.Display} was slain in the fall of {loser.Name}.", "COURT");
            }
            else
            {
                WorldData.LogEvent($"{leader.Display} has fled into exile as {loser.Name} fell to {victorName}.", "COURT");
            }
        }

        // ─── Debug ────────────────────────────────────────────────────────────────

        public static string BuildCourtReport()
        {
            var lines = new List<string>();
            foreach (var kv in WorldData.CurrentState.Factions)
            {
                var d = kv.Value;
                if (string.IsNullOrEmpty(d.Name)) continue;
                bool gone = WorldData.CurrentState.EliminatedFactions.Contains(kv.Key);
                string leader = d.Leader != null
                    ? $"{d.Leader.Display}{(d.Leader.IsDead ? " †" : "")}{(!string.IsNullOrEmpty(d.Leader.Trait) ? $" ({d.Leader.Trait})" : "")}"
                    : "(no court yet)";
                string lts = d.Lieutenants != null && d.Lieutenants.Count > 0
                    ? string.Join(", ", d.Lieutenants.Select(l => l.Display + (l.IsDead ? " †" : "")))
                    : "none";
                string former = d.FormerLeaders != null && d.FormerLeaders.Count > 0
                    ? $"\n    formerly: {string.Join(", ", d.FormerLeaders)}" : "";
                lines.Add($"{d.Name}{(gone ? " [FALLEN]" : "")}\n  Leader: {leader}\n  Lieutenants: {lts}{former}");
            }
            return lines.Count > 0 ? string.Join("\n", lines) : "No faction courts exist yet.";
        }
    }
}
